module.exports = [
  {
    id: 1,
    title: "1 bedroom flat, furnished, in Little Venice",
    postcode: "W9 2HF",
    address: "47 Sutherland Avenue, London",
    agency: "Chestnuts",
    bedrooms: 1,
    reception: true,
    pets: false,
    outdoor: false,
    picture:
      "https://firebasestorage.googleapis.com/v0/b/escaperoom-de5f1.appspot.com/o/flat12.jpeg?alt=media&token=b7da36a7-61eb-4f9e-9d3f-a00c0333175f",
  },
  {
    id: 2,
    title: "2 bedroom house with garden in Gwynedd",
    postcode: "LL52 0BN",
    address: "123 Main Street, Gwynedd",
    agency: "Richester",
    bedrooms: 2,
    reception: true,
    pets: true,
    outdoor: true,
    picture:
      "https://firebasestorage.googleapis.com/v0/b/escaperoom-de5f1.appspot.com/o/flat13.jpeg?alt=media&token=8d1fea4f-df98-417d-8e9b-b21984ee0999",
  },
  {
    id: 3,
    title: "Spacious 3 bedroom flat in Truro",
    postcode: "TR1 2NH",
    address: "456 High Street, Truro",
    agency: "Chestnuts",
    bedrooms: 3,
    reception: true,
    pets: false,
    outdoor: true,
    picture:
      "https://firebasestorage.googleapis.com/v0/b/escaperoom-de5f1.appspot.com/o/flat14.jpeg?alt=media&token=43e8db26-04f4-4bae-a7b7-610d3fa91b3a",
  },
  {
    id: 4,
    title: "4 bedroom townhouse in Hull",
    postcode: "HU9 3NB",
    address: "789 Waterfront Road, Hull",
    agency: "Richester",
    bedrooms: 4,
    reception: true,
    pets: true,
    outdoor: true,
    picture:
      "https://firebasestorage.googleapis.com/v0/b/escaperoom-de5f1.appspot.com/o/flat15.jpeg?alt=media&token=8a1bf9cd-f73e-41bf-a843-2dc8cbc2750d",
  },
  {
    id: 5,
    title: "Luxury apartment near Richmond Park",
    postcode: "TW9 2AD",
    address: "101 Park Avenue, Richmond",
    agency: "Chestnuts",
    bedrooms: 2,
    reception: true,
    pets: false,
    outdoor: true,
    picture:
      "https://firebasestorage.googleapis.com/v0/b/escaperoom-de5f1.appspot.com/o/flat16.jpeg?alt=media&token=5c3dc77f-37b5-40cf-904e-ff2d3932c74e",
  },
  {
    id: 6,
    title: "Modern studio apartment in Belfast",
    postcode: "BT40 3HB",
    address: "15 Victoria Street, Belfast",
    agency: "Richester",
    bedrooms: 1,
    reception: false,
    pets: true,
    outdoor: false,
    picture:
      "https://firebasestorage.googleapis.com/v0/b/escaperoom-de5f1.appspot.com/o/flat17.jpeg?alt=media&token=081cfea2-0975-4be1-8e76-fca83dcd3b90",
  },
  {
    id: 7,
    title: "Charming cottage near York",
    postcode: "YO61 2NW",
    address: "25 Countryside Lane, York",
    agency: "Chestnuts",
    bedrooms: 2,
    reception: true,
    pets: true,
    outdoor: true,
    picture:
      "https://firebasestorage.googleapis.com/v0/b/escaperoom-de5f1.appspot.com/o/flat18.jpeg?alt=media&token=2b1af750-e331-47b1-b48b-4c0acb15c366",
  },
  {
    id: 8,
    title: "Stylish loft apartment in Hereford",
    postcode: "HR1 3RD",
    address: "8 Mill Street, Hereford",
    agency: "Foxters",
    bedrooms: 1,
    reception: true,
    pets: false,
    outdoor: false,
    picture:
      "https://firebasestorage.googleapis.com/v0/b/escaperoom-de5f1.appspot.com/o/flat19.jpeg?alt=media&token=52054dd3-daf8-4ff6-836c-621fe2ca6682",
  },
  {
    id: 9,
    title: "Family home in Hertfordshire",
    postcode: "SG12 9AX",
    address: "12 Maple Avenue, Hertford",
    agency: "Foxters",
    bedrooms: 4,
    reception: true,
    pets: true,
    outdoor: true,
    picture:
      "https://firebasestorage.googleapis.com/v0/b/escaperoom-de5f1.appspot.com/o/flat20.jpeg?alt=media&token=8d975255-d519-4d19-af61-ab4d25778403",
  },
  {
    id: 10,
    title: "Cosy apartment in Bristol",
    postcode: "BS16 2JH",
    address: "7 Harbour Road, Bristol",
    agency: "Homptons",
    bedrooms: 1,
    reception: true,
    pets: false,
    outdoor: true,
    picture:
      "https://firebasestorage.googleapis.com/v0/b/escaperoom-de5f1.appspot.com/o/flat21.jpeg?alt=media&token=bc188d67-d787-4893-a070-6394945d9775",
  },
  {
    id: 11,
    title: "Overrated kitchen with built-in bed",
    postcode: "W1 Y78",
    address: "7 Harbour Road, Paddington",
    agency: "Richester",
    bedrooms: 1,
    reception: true,
    pets: false,
    outdoor: true,
    picture:
      "https://firebasestorage.googleapis.com/v0/b/escaperoom-de5f1.appspot.com/o/flat22.jpeg?alt=media&token=c953a4b1-65b7-4c41-a03c-a024cc31b277",
  },
  {
    id: 12,
    title: "Ourageous penthouse in Hydepark",
    postcode: "EC2 2JH",
    address: "7 Harbour Road, London",
    agency: "Homptons",
    bedrooms: 5,
    reception: true,
    pets: false,
    outdoor: true,
    picture:
      "https://firebasestorage.googleapis.com/v0/b/escaperoom-de5f1.appspot.com/o/flat25.jpeg?alt=media&token=d998aa8e-15ef-4b63-a538-95f5bf35fce3",
  },
];
