module.exports = [
  {
    id: 1,
    title: "1 bedroom flat, furnished, in Little Venice",
    postcode: "W9 2HF",
    address: "47 Sutherland Avenue, London",
    agency: "Chestertons",
    bedrooms: 1,
    reception: true,
    pets: false,
    outdoor: false,
    price: 1900,
  },
  {
    id: 2,
    title: "2 bedroom house with garden in Gwynedd",
    postcode: "LL52 0BN",
    address: "123 Main Street, Gwynedd",
    agency: "Gwynedd Properties",
    bedrooms: 2,
    reception: true,
    pets: true,
    outdoor: true,
    price: 1300,
  },
  {
    id: 3,
    title: "Spacious 3 bedroom flat in Truro",
    postcode: "TR1 2NH",
    address: "456 High Street, Truro",
    agency: "Cornwall Estates",
    bedrooms: 3,
    reception: true,
    pets: false,
    outdoor: true,
    price: 2200,
  },
  {
    id: 4,
    title: "4 bedroom townhouse in Hull",
    postcode: "HU9 3NB",
    address: "789 Waterfront Road, Hull",
    agency: "Hull Properties",
    bedrooms: 4,
    reception: true,
    pets: true,
    outdoor: true,
    price: 2800,
  },
  {
    id: 5,
    title: "Luxury apartment near Richmond Park",
    postcode: "TW9 2AD",
    address: "101 Park Avenue, Richmond",
    agency: "Richmond Estates",
    bedrooms: 2,
    reception: true,
    pets: false,
    outdoor: true,
    price: 3500,
  },
  {
    id: 6,
    title: "Modern studio apartment in Belfast",
    postcode: "BT40 3HB",
    address: "15 Victoria Street, Belfast",
    agency: "Belfast Realty",
    bedrooms: 1,
    reception: false,
    pets: true,
    outdoor: false,
    price: 1200,
  },
  {
    id: 7,
    title: "Charming cottage near York",
    postcode: "YO61 2NW",
    address: "25 Countryside Lane, York",
    agency: "Yorkshire Homes",
    bedrooms: 2,
    reception: true,
    pets: true,
    outdoor: true,
    price: 1600,
  },
  {
    id: 8,
    title: "Stylish loft apartment in Hereford",
    postcode: "HR1 3RD",
    address: "8 Mill Street, Hereford",
    agency: "Hereford Living",
    bedrooms: 1,
    reception: true,
    pets: false,
    outdoor: false,
    price: 1400,
  },
  {
    id: 9,
    title: "Family home in Hertfordshire",
    postcode: "SG12 9AX",
    address: "12 Maple Avenue, Hertford",
    agency: "Hertfordshire Properties",
    bedrooms: 4,
    reception: true,
    pets: true,
    outdoor: true,
    price: 2500,
  },
  {
    id: 10,
    title: "Cosy apartment in Bristol",
    postcode: "BS16 2JH",
    address: "7 Harbour Road, Bristol",
    agency: "Bristol Rentals",
    bedrooms: 1,
    reception: true,
    pets: false,
    outdoor: true,
    price: 1100,
  },
];
