module.exports = [
  {
    id: 1,
    condition: 4,
    confort: 3,
    safety: 5,
    management: 1,
    comments:
      "Beautiful and nice location, the flat has some mold issues that are difficult to repair. The letting agent takes a lot of time to fix or repair anything in the flat and when it does, always the cheapest useless solution. It is a really small overpriced flat, old and not very well maintained. During the 2 years we rented this flat they didn't raise the price, which is nice, but they tried to take advantage of our deposit and we had to complain with photos and evidence to prove we didn't damage anything. We won't repeat with the same letting agent.",
    price: 1780,
    date: 2021,
    picture: "https://picsum.photos/200",
  },
  {
    id: 2,
    condition: 4,
    confort: 5,
    safety: 4,
    management: 5,
    comments:
      "Furniture was well-maintained and comfortable. Excellent thermal insulation and noise reduction. Management was top-notch, addressing concerns promptly. The area is safe and has excellent connectivity. They asked to raise the price more than 20% after the first year so we decided to leave.",
    price: 2340,
    date: 2019,
    picture: "https://picsum.photos/200",
  },
  {
    id: 3,
    condition: 1,
    confort: 1,
    safety: 3,
    management: 1,
    comments:
      "The furniture was in poor condition, needing immediate attention. Comfort was compromised due to poor thermal insulation and noise issues. Management was lacking; maintenance requests were often ignored. Safety and connectivity were average. The letting agent tried to scam us with the deposit, we got it back after 3 months.",
    price: 1320,
    date: 2022,
    picture: "https://picsum.photos/200",
  },
  {
    id: 4,
    condition: 4,
    confort: 4,
    safety: 4,
    management: 4,
    comments:
      "The property was unfurnished but the finishes were in great condition. The property had excellent thermal insulation and noise reduction. The heating failed a couple of times in winter but itwas fixed quickly. The landlord's management was attentive and quick to address any issues. The area is safe and offers great connectivity.",
    price: 1970,
    date: 2022,
    picture: "https://picsum.photos/200",
  },
  {
    id: 5,
    condition: 4,
    confort: 3,
    safety: 2,
    management: 5,
    comments:
      "Furniture was well-kept and added to the overall comfort. Thermal insulation was good, and noise insulation was satisfactory despite the near location of a tube station. There was a leak from the flat upstairs that damaged our ceiling but it was solved. The landlord's management was excellent. The area is not very safe, I was scared to walk alone at night.",
    price: 2530,
    date: 2020,
    picture: "https://picsum.photos/200",
  },
  {
    id: 6,
    condition: 5,
    confort: 5,
    safety: 4,
    management: 5,
    comments:
      "The furniture was in excellent condition. Everything felt new and well-maintained. The thermal insulation kept the place cozy, and noise insulation was impressive. The landlord's management was great, always prompt in addressing issues. The area is safe and well-connected. The property was sold so we they terminated our contract early.",
    price: 3600,
    date: 2017,
    picture: "https://picsum.photos/200",
  },
  {
    id: 7,
    condition: 3,
    confort: 2,
    safety: 3,
    management: 3,
    comments:
      "The furniture needed some updates, but overall, it was acceptable. The comfort level was good, especially the heating. Noise insulation could be better. Management was average; responses were delayed at times. The area feels safe but lacks good connectivity. They never raised the rent in 3 years, there was a good relationship between us, the tenants, and the landlord.",
    price: 1120,
    date: 2023,
    picture: "https://picsum.photos/200",
  },
  {
    id: 8,
    condition: 3,
    confort: 2,
    safety: 4,
    management: 3,
    comments:
      "Furniture was a mix of old and new. Comfort was decent, but noise insulation was lacking. Single glazing only and old sash windows. Management was responsive, but there were some maintenance delays. The area is safe, with good connectivity to amenities. Only buses in the area, no tube.",

    price: 1360,
    date: 2018,
    picture: "https://picsum.photos/200",
  },
  {
    id: 9,
    condition: 3,
    confort: 2,
    safety: 4,
    management: 3,
    comments:
      "The furniture needed some improvements, but it was comfortable. Thermal insulation was decent, but noise insulation could be better. Management was average; responses were slow. The area is safe, and connectivity is convenient.",
    price: 1580,
    date: 2023,
    picture: "https://picsum.photos/200",
  },
  {
    id: 10,
    condition: 3,
    confort: 4,
    safety: 4,
    management: 3,
    comments:
      "Furniture was in good condition and added to the comfort. The property had excellent thermal insulation and noise reduction. Management was efficient and responsive. The area is safe but very far away from amenities and transport links.",
    price: 1360,
    date: 2018,
    picture: "https://picsum.photos/200",
  },
];
